eureka:
  instance:
    hostname: localhost
  environment: default
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: accounts-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:BANK_DB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 9080
management:
  security:
    enabled: false