server:
  port: 8080

spring:
  profiles: default
  application:
    name: edge-service

zuul:
  ignored-services: '*'
  routes:
    accounts-service:
      path: /**
      sensitiveHeaders: Cookie,Set-Cookie

eureka:
  instance:
    hostname: localhost
  environment: default
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  ServerListRefreshInterval: 500

spring.metrics.servo.enabled: false